controller_manager:
  ros__parameters:
    update_rate: 10 # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    left_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    right_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

left_arm_controller:
  ros__parameters:
    joints:
      - left_shoulder_joint
      - left_upper_arm_joint
      - left_lower_arm_joint
      - left_wrist_joint
      - left_palm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 20.0
    action_monitor_rate: 20.0

right_arm_controller:
  ros__parameters:
    joints:
      - right_shoulder_joint
      - right_upper_arm_joint
      - right_lower_arm_joint
      - right_wrist_joint
      - right_palm_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
    state_publish_rate: 20.0
    action_monitor_rate: 20.0
